import os
class Settings:
    APP_NAME = os.getenv("APP_NAME", "CourtneySignals")
    ENV = os.getenv("ENV", "dev")
    PORT = int(os.getenv("PORT", "8000"))
    JWT_SECRET = os.getenv("JWT_SECRET", "devsecret")
    JWT_EXPIRES_MIN = int(os.getenv("JWT_EXPIRES_MIN", "43200"))
    DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./dev.db")
    SMTP_HOST = os.getenv("SMTP_HOST", "")
    SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
    SMTP_USER = os.getenv("SMTP_USER", "")
    SMTP_PASS = os.getenv("SMTP_PASS", "")
    SMTP_FROM = os.getenv("SMTP_FROM", "")
    SUPERADMIN_EMAIL = os.getenv("SUPERADMIN_EMAIL", "admin@example.com")
    SUPERADMIN_PASSWORD = os.getenv("SUPERADMIN_PASSWORD", "Admin#123")
    SUPERADMIN_NAME = os.getenv("SUPERADMIN_NAME", "Super Admin")
    TIMEZONE = os.getenv("TIMEZONE", "Asia/Kolkata")
    CRON_SHARED_SECRET = os.getenv("CRON_SHARED_SECRET", "changeme")
settings = Settings()